# Generated by Django 4.2.7 on 2023-12-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('prosent', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='resumeapp.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.message', verbose_name='Message'),
        ),
    ]
