# Generated by Django 4.2.7 on 2023-12-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_message_skill_alter_contact_options_skills_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
    ]
