# Generated by Django 4.2.7 on 2023-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_project_title_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='message',
        ),
        migrations.AddField(
            model_name='blog',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='resumeapp.message', verbose_name='Message'),
        ),
    ]
